### ISSUE TITLE
Sparkles

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#221]
### Description

As a developer using Tresjs I would like to have a simple way to add sparkles as a component

### Suggested solution

Similar to: https://github.com/pmndrs/drei#sparkles

### Alternative

Any other alternative is considered

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
@JaimeTorrealba 

## What does a "sparkle" look like?

Here's the Drei component:

https://github.com/Tresjs/cientos/assets/20469369/2ca68a1f-b56b-44f4-bbdd-92c1bc14188f

To me, it doesn't really "sparkle". Part of the effect is due to props, part to the shader itself. Playing with the props, I can't get the "sparkles" to flash -> fade out.

This is more of a "sparkle" – flash -> fade out:

https://github.com/Tresjs/cientos/assets/20469369/7fe14086-5482-4733-9a99-809b16cfb8f5

## Use Geometry?

**Should we add a "geometry" prop so that the user can match the shape of the "sparkling" component?**

The Drei component distributes the starting positions of the sparkles in a scaled cube. That looks pretty obvious when there are a lot of sparkles and the "sparking" shape isn't also a cube.

https://github.com/Tresjs/cientos/assets/20469369/9b276822-3f70-4ac9-b8b3-a219af49b743

Instead, we could use vertex data, like so:

https://github.com/Tresjs/cientos/assets/20469369/92026a1b-cf0b-48de-a2f8-111a613a5f60

E.g., here's how this is called:

```
<script setup lang="ts">
import { TresCanvas } from '@tresjs/core'
import { OrbitControls, Sparkles, TorusKnot} from '@tresjs/cientos'
import { SRGBColorSpace, NoToneMapping, SphereGeometry, TorusKnotGeometry } from 'three'

const gl = {
  clearColor: '#333',
  alpha: true,
  outputColorSpace: SRGBColorSpace,
  toneMapping: NoToneMapping,
}

const sparkleGeom = new TorusKnotGeometry(1)
const positions = sparkleGeom.getAttribute('position').array
</script>

<template>
  <TresCanvas
    v-bind="gl"
  >
    <TresPerspectiveCamera :position="[0, 2, 5]" />
    <TorusKnot :args="[1]">
      <TresMeshToonMaterial color="#82DBC5" />
      <Sparkles :geometry="positions" :noise="[1.1, 1., 1.1]" :speed="2" :translation="[0.1, 0.3, 0.1]" :size="4" color="#82DBC5" />
    </TorusKnot>
    <TresGridHelper :args="[10, 10]" />
    <TresAmbientLight :intensity="1" />
    <TresDirectionalLight
      :intensity="1"
      :position="[2, 2, 2]"
    />
    <OrbitControls />
  </TresCanvas>
</template>
```

It doesn't add *a lot* of code for the end user, but it would be harder to use than other Cientos components. Since the focus in on DX, I wonder if it's worth complicating the code to offer the prop?

The user would have to understand that the sparkles emit from the vertices. The more vertices, the more sparkles. It's not just a question of changing a number on the prop directly, like with the original Drei setup.

Or is there another pattern that Tres/Cientos uses for this sort of thing? (I looked an couldn't find one.)

What do you think?

**Comment by andretchen0** [comment]
> How can we get rid of the :geometry prop a pass it automatically... For me if I'm using a Torus geometry the sparkles would need to understand and use the same geometry by default.... what do you think?

Yes, I think we can do that. Maybe we use this order of precedence:

1) explicit `:geometry` prop
2) parent element's `geometry`
3) use a "cube" like the Drei implementation and `:count` prop

For example, I might want to include a "sparkling" area that's a different shape than my geometry or that contains more or fewer vertices.

> Have you tried to access to the parent with the .parent property provided by isObject3D?

Yes. That works.

----

## How to represent particle color, opacity, scale?

> Do you contemplate a prop for just no fade the particles? (I like them more when fade them, but maybe there are people who don't need the fade effect)

I'd like it to be flexible like that. I'm not sure what fits best in the project. 

Following the Drei example, the user can either specify a single color for all particles or a specific color for each particle. I'm not sure how useful it is to allow the user specify colors for each particle.

We could linearly interpolate between values over the lifetime of a particle. For example, color could be represented by:

```
<Sparkles :color="['red', 'white', 'green']" />
```

But the usual approach for this sort of thing in consumer software would be something like this on the UI side:

<img width="307" alt="Screenshot 2023-10-04 at 20 51 21" src="https://github.com/Tresjs/cientos/assets/20469369/07d1d51c-cdb1-48f5-8915-961090ea2986">

For Cientos, in data, that might look like:

```
<Sparkles :color="[['red', 0.1], ['white', 0.2], ['green', 0.6]]" />
```

That's a little harder to write for the user though. Maybe Leches could offer a widget eventually.

@JaimeTorrealba, do you have a preference here? I can support all of these for color:

`color: TresColor | TresColor[] | Array<[TresColor, number]`

... but I don't want to complicate the code unnecessarily.

**Comment by JaimeTorrealba** [comment]
This is already in Cientos, any problem if I close it? @andretchen0

**Comment by andretchen0** [comment]
> This is already in Cientos, any problem if I close it? @andretchen0 

No problem.

Glad to see you're back!
