### ISSUE TITLE
Sprite component

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#247]
### Description

As a developer using Tresjs I would like to create sprite animations by cycling through a sequence of frames from a sprite sheet image or JSON data, so I could add sprites images to my 3D spaces.

### Suggested solution

Inspired by: https://github.com/pmndrs/drei#sprite-animator

### Alternative

Feel free to suggest other alternatives

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
Not sure if it'd be useful here, but this is the nicest way that I've come across to declare sprite animations in code:

https://github.com/deepnight/deepnightLibs/blob/144e494fc405766a570fad5bd20c27c806e6282d/src/dn/heaps/slib/SpriteLib.hx#L544

If you name your images "idle0.png", "idle1.png", "idle2.png", "walk0.png", "walk1.png". Then, when you declare your e.g., idle animation, you can specify order and delay:

```
defineAnim( "idle", "0-2, 0(2), 1" );
```

So the animation above would show images 0-2 for 1 frame each, then frame 0 for 2 frames, then frame 1.

**Comment by andretchen0** [comment]
@JaimeTorrealba @alvarosabu 

I'll take this. (I see it's marked "Good Beginner Issue", but I'd really like to see if I can improve on the DX of the Drei version.)

## Questions

The Drei version accepts a JSON texture atlas / packed sprites. 

* **Do you have a preference for a particular piece of software for creating those files?**
* **Or is there a particular atlas spec we should use?**

Otherwise, some options:

* [LibGDX TexturePacker](https://libgdx.com/wiki/tools/texture-packer) – This is a free standalone GUI. Maybe users would have a tough time getting it to work – I believe users will have to install a JRE if they don't have one.
* Roll our own – An inefficient but ok-for-our-purposes command line texture packer isn't very hard to write, assuming we add an image processing dependency – [I've had good luck with Sharp.](https://www.npmjs.com/package/sharp) But I don't want to make Cientos responsible for continued support unless that's the way you guys want to go.
* Do nothing – Let users figure it out on their own. And type out a sprite atlas if that's what they want.

**Comment by damienmontastier** [comment]
Hey @andretchen0 ✌ ! I don't know if you know [TexturePacker](https://www.codeandweb.com/texturepacker), I've used it a few times and it's always been quick and easy to use.

**Comment by andretchen0** [comment]
> Hey @andretchen0 ✌ ! I don't know if you know [TexturePacker](https://www.codeandweb.com/texturepacker), I've used it a few times and it's always been quick and easy to use.

@damienmontastier 

Thanks for the recommendation!

I have checked out TexturePacker in the past and it's a great tool. Maybe one of the others can chime in to the contrary if I'm wrong, but I think for Tres/Cientos, we'd want to have a free – but ideally FOSS – tool that people could use.

**Comment by andretchen0** [comment]
Closing: completed.
